# use it with VSCode extensions: https://marketplace.visualstudio.com/items?itemName=humao.rest-client

GET http://localhost:3000/auth/me
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IiQyYiQxMCR1M2kxUnpTZVlrTjJLZlA4ZjNTZi8uIn0.eyJ1c2VyX2lkIjoxLCJyYW5kb21pemVyIjoxNzIxNzg5NTc4NTE2LCJ0b2tlbl9pZCI6IiQyYiQxMCR1M2kxUnpTZVlrTjJLZlA4ZjNTZi8uIiwiaWF0IjoxNzIxNzg5NTc4LCJleHAiOjE3MjE4MTExNzh9.aiCaVSsqanQC_7KwpoBIDwB85PwsK6dXtQUMS3yy6HM

###

POST http://localhost:3000/auth/login
content-type: application/json

{
    "email": "super.admin@admin.com",
    "password": "password"
}

###

POST http://localhost:3000/auth/register
content-type: application/json

{
    "email": "sysafarila@email.com",
    "password": "password",
    "name": "Syahrul"
}
