# use it with VSCode extensions: https://marketplace.visualstudio.com/items?itemName=humao.rest-client

POST http://localhost:3000/auth/login
content-type: application/json

{
    "email": "sysafarila@email.com",
    "password": "password"
}

###

POST http://localhost:3000/auth/register
content-type: application/json

{
    "email": "sysafarila@email.com",
    "password": "password",
    "name": "Syahrul"
}
