name: Node.js CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - run: docker run --detach --name myMariaDb -e MARIADB_ROOT_PASSWORD=password -e MARIADB_DATABASE=node mariadb:latest
        env:
          DATABASE_URL: mysql://root:password@localhost:3306/node
      - run: npm ci
      - run: npx prisma migrate deploy
      - run: npm test
