name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - run: docker run --name mydatabase -e MARIADB_ROOT_PASSWORD=password -e MARIADB_DATABASE=node -d -p 3306:3306 mariadb:latest
        env:
          DATABASE_URL: mysql://root:password@localhost:3306/node
      - run: npm ci
      - run: cp .env.github .env
      - run: npx prisma generate
      - run: npx prisma migrate deploy
      - run: npx prisma db seed
      - run: npm test
