name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - run: docker compose up -d
      - run: npm ci
      - run: cp .env.github .env
      - run: npx prisma generate
      - run: npx prisma migrate deploy
      - run: npx prisma db seed
      - run: npm test
      - run: docker compose down